### ISSUE TITLE
ERROR - MySQL STRICT MODE on Aksara 4.2.4

### ISSUE THREAD

**Issue by cakmoel** [abydahana/Aksara#3]
OS: Ubuntu 18.04 LTS 
 PHP 7.4
MySQL 5.7 

Error in MySQL 5.7 and above.  

mysqli_sql_exception: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'aksara.blogs__categories.category_slug' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /DOC_ROOT/aksara/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:314 

Please do not give a solution to disable sql_mode -- Write the correct SQL!

**Comment by abydahana** [comment]
> Please do not give a solution to disable sql_mode -- Write the correct SQL!

Hello, could you please give me the details of module or page that throw this error?

**Comment by abydahana** [comment]
Ah got it. It's because we used to select with asterisks. We are now working with ONLY_FULL_GROUP_BY enabled so the query will be fixed for future updates.

Thanks for your suggestion.

**Comment by abydahana** [comment]
The problem has been fixed in current release version (Aksara Ra 4.2.5). You could be able to make an instant update but we recommend to fresh install these version if you have an issue related to the updater.

[https://github.com/abydahana/Aksara/releases/tag/v4.2.5](https://github.com/abydahana/Aksara/releases/tag/v4.2.5)
