### ISSUE TITLE
count in set_relation function with reference id & where not working

### ISSUE THREAD

**Issue by Nazamla** [abydahana/aksara#311]
![unnamed2](https://user-images.githubusercontent.com/7930224/197968813-2fa24098-f10d-42cc-bf3f-08e105a91370.png)
![unnamed1](https://user-images.githubusercontent.com/7930224/197968832-29fc94a1-0a8d-4307-ba52-9c26297d88a8.png)
![unnamed](https://user-images.githubusercontent.com/7930224/197968880-e77dfacc-4be3-466a-9283-202defd73330.png)

**Comment by abydahana** [comment]
Thank you for reporting this issue. I’m now working on it and will be fix it in next version.

**Comment by abydahana** [comment]
Hello @Nazamla. Turn out you have incorrect parameter with the `set_relation` method usage. Since the `count` result is an optional record that should not hiding the parent result when the `count` is empty, it's ideally to using the subquery under the `select` method or you can alternatively using `LEFT JOIN` just like below:

```php
->select('COUNT(app__users_ld_designs.ldi_id) AS count')
->join('app__users_ld_designs', 'app__users_ld_designs.ldi_id = parent__table.id AND app__users_ld_designs.status2 IS NULL', 'LEFT')
```
